### ISSUE TITLE
Using Guzzle, PHP HTTP client

### ISSUE THREAD

**Issue by peter279k** [eldadfux/mailgun-php-lite#2]
Hi, thank you providing this lightweight MailGun library!
It seems that it uses the native ```curl``` function to handle the HTTP request.
Have you ever thought about using the [Guzzle](https://github.com/guzzle/guzzle) before?It can be easier than using the ```curl``` functions.

If possible, I can help this.

Thanks!

**Comment by eldadfux** [comment]
Hi Peter, thank you for your feedback.

My main goal when creating this library as an alternative to the official SDK was to write something lean, simple to use and learn and **dependency free**.

Although Guzzle is great and I have used for different projects in the past I have preferred to keep it simple.

I think it might be a good idea to ask the official SDK to add support for a Guzzle client.
